ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "estimatedNoiseScore" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "estimatedLightingScore" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "estimatedCrowdScore" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "dataSource" TEXT NOT NULL DEFAULT 'category';
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "externalYelpId" TEXT;
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "lastEnrichedAt" TIMESTAMP(3);
ALTER TABLE "Location" ADD COLUMN IF NOT EXISTS "enrichmentConfidence" DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS "EnrichmentLog" (
    "id" TEXT NOT NULL,
    "locationId" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "scores" JSONB NOT NULL,
    CONSTRAINT "EnrichmentLog_pkey" PRIMARY KEY ("id")
);
