ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "temperature" JSONB;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "seating" JSONB;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "bathrooms" JSONB;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "socialInteractions" JSONB;
